### ISSUE TITLE
Using template instead of rtemplate

### ISSUE THREAD

**Issue by dahmian** [yeojz/metalsmith-react-templates#1]
Hi, thanks for writing this plugin, it's really useful! I'm curious though, why pull from rtemplate instead of template?

**Comment by yeojz** [comment]
@dahmian thanks.

Pulling from `rtemplate` was to give flexibility and maintain compatibility with other templating engines. 
It was to support the use case  where you may want to use `React` to modify your content, but still take advantage of other functionalities which templating engines may provide.

I do not know if it will be a common use case though. So I erred on the side of caution.

**Comment by dahmian** [comment]
Thank you for explaining! That sounds like an interesting use case, so you could embed a React template inside another template like the example below? That might be useful for rendering tags that React does not support. Or if you want to do something that React doesn't allow, like having two root nodes. Are there other use cases?

**index.html**:
```
---
template: master.mustache
rtemplate: detail.jsx 
---
Hello World!
```

**detail.jsx**:
```
var React = require('react'); 
module.exports = React.createClass({
  render: function() {
    return <p>{this.props.content}</p>
  }
});
```
**master.mustache**:
```
<customtag>
  {{{ contents }}} 
</customtag>
```

**Comment by yeojz** [comment]
@dahmian Great example! Yes. That's about it. I didn't even consider 2 root nodes actually..

The initial thought started from needing to insert the contents of metalsmith somewhere. In an actual React app, that will be an index.html which calls:
```js
React.render(<Handler/>, document.getElementById('container'));
```
In the case of this plugin, it's the `base.html` file

However, this solution will not give the option of having multiple base templates for different sections of the site or have the option of logic (like if-else) statements. For example in in lodash:

```js
<% if (typeof(title) !== "undefined") { %> Do Something <% } %>
```

This is something I didn't want to recreate as it's not the main purpose of the plugin.

So you can turn off the `base.html` option and choose to use say `metalsmith-templates` to do the final html file rendering with all the power of html templating if desired.
