### ISSUE TITLE
Git Ignoring Main Entry Point?

### ISSUE THREAD

**Issue by EvanLovely** [yeojz/metalsmith-react-templates#14]
In your [package.json file, you have `lib/index.js` as your `main` entry](https://github.com/yeojz/metalsmith-react-templates/blob/master/package.json#L5) and the `lib/`folder is in [`.gitignore`](https://github.com/yeojz/metalsmith-react-templates/blob/master/.gitignore#L15) – is that intentional?

**Comment by yeojz** [comment]
Yes. It's intentional. 

`lib` is the build folder which will be built as a pre-publishing step.
If you're developing on the repository, you should run `npm run build` to compile the code.

**Comment by EvanLovely** [comment]
OK, good to know! Cheers! :beers:
