### ISSUE TITLE
Update to React 0.14

### ISSUE THREAD

**Issue by cameronjroe** [yeojz/metalsmith-react-templates#15]
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by cameronjroe** [comment]
Any update on this? Would love to use this plugin.

**Comment by yeojz** [comment]
Hi @cameronjroe 

Apologies. I'm a little occupied at work, so no timeline on this yet.

Gerald.

**Comment by cameronjroe** [comment]
@yeojz Is there anything I can do to help? Would love to get this working. React is ideal for templating. Currently suffering with liquid right now.. lol

**Comment by yeojz** [comment]
@cameronjroe apologies for the long wait....
Updates are now in `master`

**Comment by cameronjroe** [comment]
Cool, thanks.
