### ISSUE TITLE
Doesn't seem to work with React >= 0.13 + JSX + ES6

### ISSUE THREAD

**Issue by pm5** [yeojz/metalsmith-react-templates#3]
One of our projects used React 0.13.1 with JSX and ES6.  When building metalsmith the following warning was raised:

> Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
> .../build.es6:34
>   if (err) throw err;
>                  ^
> Error: Invariant Violation: renderToString(): You must pass a valid ReactElement.
>     at invariant (.../node_modules/metalsmith-react-templates/node_modules/react/lib/invariant.js:42:15)
>     at Object.renderToString (.../node_modules/metalsmith-react-templates/node_modules/react/lib/ReactServerRendering.
> js:28:44)
>     at renderReactTemplate (.../node_modules/metalsmith-react-templates/lib/index.js:73:42)
> ...

Downgrade to React 0.12.x and everything was fine.

This is probably because in React 0.13, if you use JSX you must not wrap the component with `React.createFactory()`.  But I am not 100% sure if this was the cause.

**Comment by jamiecollinson** [comment]
I can confirm - I also had the same issue. Downgrading to React 0.12.2 (as in the example) fixed for me.

**Comment by yeojz** [comment]
Will look into this and try and reproduce it.

One clarification thought... Are the file extensions `.jsx` or is it something else? I noticed the snippet above was using `build.es6`

If anyone has a fix feel free to share as well. 

@pm5 I noticed you added a `requireIgnore` for webpack as well. Is that a common issue also?

**Comment by jamiecollinson** [comment]
I don't know about @pm5 but I was using `.jsx` extensions for templates.

**Comment by yeojz** [comment]
@pm5 and @jamiecollinson 

I've updated the dependencies and the component creation process in `upgrade-react-0.13` branch.
I've added babel transformation option to allow better es6 support as well.

Would be great if you guys can try it out and see if it fixes your issues.

Thanks

**Comment by yeojz** [comment]
Changes released in v0.2.0
