### ISSUE TITLE
reactTemplate is not a function

### ISSUE THREAD

**Issue by chadhahn** [yeojz/metalsmith-react-templates#40]
Upgrading the "example" app to version 5.0.1 and build.js throws "reactTemplate is not a function". What is the process to migrate to the new version?

**Comment by yeojz** [comment]
@chadhahn 
It should work if you replace `require('metalsmith-react-templates')` with ` require('metalsmith-react-templates').default`

This is due a change in the behaviour of `babel` which removed default `module.exports`  assignment. (https://github.com/babel/babel/issues/2212)

Haven't had the time to update the examples yet. Will add an `interop` file in a future release to make it more explicit.

**Comment by yeojz** [comment]
@chadhahn 

Already released a `require('metalsmith-react-templates/interop')` before v6. 
Will be closing this. 

If you're still facing any issues, don't hesitate to open a new issue. Thanks.
