### ISSUE TITLE
Use of templateTag?

### ISSUE THREAD

**Issue by benpolinsky** [yeojz/metalsmith-react-templates#54]
Hi,

I'm attempting to use a different templateTag to render my contents into, but I'm having difficulty getting anything to work. 

Do you just pass a function to templateTag?

`
reactTemplates({
  templateTag: function(key){return new RegExp(pattern, 'g')}
})
`

Looking through the code, I couldn't find the part where you were checking the options and applying a new templateTag based on this function.

**Comment by yeojz** [comment]
Hi @benpolinsky 

Yes that is correct. The default is 
```js
const DEFAULT_PATTERN = (key) => (
  new RegExp(`{{${key}}}`, 'g')
);
```
and it can be found here:
https://github.com/yeojz/metalsmith-react-templates/blob/master/src/jsx-render-engine/strategy/naive.js

It will be called when we're replacing values in the baseFile 
https://github.com/yeojz/metalsmith-react-templates/blob/master/src/jsx-render-engine/utils/applyBaseFile.js

**Comment by yeojz** [comment]
Closing this.
Please re-open if you still have issues.
