### ISSUE TITLE
Access Site Metadata

### ISSUE THREAD

**Issue by benpolinsky** [yeojz/metalsmith-react-templates#55]
Any way to access site metadata in jsx?

**Comment by benpolinsky** [comment]
So I found it in props.metadata.

This may be outside of your scope, but what are you thoughts about displaying the metadata in the site's header? So, for instance, displaying the title of the site in the title tag.

**Comment by benpolinsky** [comment]
Okay, just rendering the head as a react component, wasn't sure if that was possible.

Thanks for your work on this plugin!

**Comment by yeojz** [comment]
Another way is to use something like react-helmet.

**Comment by benpolinsky** [comment]
Oh yeah, I forgot about that one. Love the name, too, coming from the devs at NFL
