### ISSUE TITLE
How would you go about supporting Helmet server-side?

### ISSUE THREAD

**Issue by Leimi** [yeojz/metalsmith-react-templates#56]
Hi,

Thanks a lot for your plugin :)

I'm using it with a simple default React setup in static mode only, but I'm having trouble making React Helmet work server-side (or I guess we should say "in static mode only" here).

I would like to be able to access [helmet instance properties](https://github.com/nfl/react-helmet#server-usage) within the html template used as `baseFile` and maybe have something like this:

```html
<!-- base.html -->
<!DOCTYPE html>
<html {{helmet.htmlAttributes}}>
	<head>
		{{helmet.title}}
		{{helmet.meta}}
		{{helmet.link}}
	</head>
	<body {{helmet.bodyAttributes}}>
		<div id="app">
			{{contents}}
		</div>
	</body>
</html>
```

My idea was to create a new strategy for jsx-render-engine that would return helmet properties in addition to the react markup. But since this is all tied to the `contents` property I don't think I can go around it. [Here is an example](https://gist.github.com/Leimi/9bfa955cac87f19eeec826564652a428) of what I tried to do. I ended up concluding that adding a way to [customize how template data was applied](https://github.com/yeojz/metalsmith-react-templates/blob/master/src/jsx-render-engine/utils/applyTemplate.js#L38) in jsx-render-engine would help.

I'm not an expert of metalsmith nor your plugin (I'm actually just getting started using both), so maybe I'm missing something obvious... sorry if that's the case.

Thanks for your help.

**Comment by yeojz** [comment]
You're right. It doesn't cover 3rd party additions in that flow..

**Comment by yeojz** [comment]
ref leimi's PR in #57
